ECS-01 feat: cria cluster ecs, service e teask definition
mentoriaiac/iac-modulo-aws-ecs pull request #2
Opened 2022-03-17 00:32 UTC by EzzioMoreira

# Titulo
Criar cluster ecs, service e task definition.

Modulo que cria cluster ECS para projetos Dados abertos de feira e mtst.

- [x] Garanta que seu **topic/feature/bugfix branch** tenha uma branch nomeada e não a sua branch main esteja no PR
- [x] Dê um titulo que expresse o objetivo do PR
- [ ] Associe seu PR a uma Issue criada no repositósito. Caso seja uma correção de linguagem ou pequenas correções, não é necessário
- [x] Descreva o objetivo do PR
- [ ] Inclua links relevantes para a sua modificação/sugestão/correção
- [ ] Descreva um passo-a-passo para testar o seu PR

## Issue

[](https://github.com/mentoriaiac/iac-modulo-aws-ecs/issues/1)

## Objetivo

Criar um cluster para os projetos Dados abertos feira e MTST.

## Referências

[](https://docs.aws.amazon.com/pt_br/AmazonECS/latest/developerguide/Welcome.html)

## Como testar

```
terraform init
terraform plan
terraform apply
```

2022-03-25 23:03 UTC, afonsoaugusto commented
Show demais o pr @EzzioMoreira e @chnacib.
Parabéns a todos os envolvidos

2022-03-25 23:42 UTC, edsoncelio commented
Boa! Tá ficando bem bom!

Só acrescentando alguns pontos:
* Dar uma olhada nas falhas do `tfsec` (se alguma delas não fizer sentido, vale [ignorar by código](https://aquasecurity.github.io/tfsec/v0.61.3/getting-started/configuration/ignores/#:~:text=Ignoring%20Checks-,Ignoring%20Warnings,above%20the%20block%2C%20by%20itself.)).
* Um dos requisitos na [demanda original](https://github.com/DadosAbertosDeFeira/maria-quiteria/issues/480) é a capacidade de uso de variáveis de ambiente vindas de algum serviço de gestão de segredos da AWS (secret manager ou parameter store por ex), só pra dar uma ideia, deixando aqui um [exemplo](https://github.com/sufleio/terraform-ecs-secrets).
* (outro ponto que é mais uma sugestão) usar alguma tool pra adicionar a linha no final dos arquivos, o [editorconfig](https://editorconfig.org/) faz isso bem demais :D

Qualquer dúvida sobre qualquer um dos pontos, só chamar lá no discord :D

2022-04-02 18:49 UTC, edsoncelio commented
cc @EzzioMoreira mais alguns checks do tfsec pra dar uma olhada :)

2022-04-03 20:06 UTC, lgfa29 requested changes
Tá ficando legal, ótimo trabalho! Deixei uns comentários de melhorias e algumas dúvidas, mas nada de muito problemático.

Acho que só precisa definir isso do cluster, se cria dentro do módulo ou não. Se for deixar opcional como está, eu acho que precisa ajustar os resources que dependem do cluster para serem opcionais também. Ficaria tipo assim:

```hcl
locals {
  cluster_count = var.create_cluster ? 1 :0
}

 resource "aws_appautoscaling_target" "ecs_target" {
  count = locals.cluster_count
  # ...
}

 resource "aws_ecs_service" "service_cluster" {
  count = local.cluster_count
  # ...
}
```

Do jeito que está eu acho que daria erro se o cluster não for criado?

2022-04-03 20:06 UTC, lgfa29 commented on README.md
> +| tags | Tags para recurso | `map(string)` | n/a | yes |
```suggestion
```

Essa linha acabou duplicada.

2022-04-03 20:06 UTC, lgfa29 commented on README.md
> +| cria\_cluster | Define se cluster será criado | `bool` | true | no |
```suggestion
| create\_cluster | Define se cluster será criado | `bool` | true | no |
```
Eu não sei se a gente já padronizou isso, mas as outras variáveis estão em inglês, então é bom seguir um padrão.

2022-04-03 20:06 UTC, lgfa29 commented on README.md
> +| [aws_ecs_service](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_service) | resource | Permite executar e manter uma simultaneamente no número especificado de tasks
> Permite executar e manter uma simultaneamente [...]

Acho que faltou uma palavra aqui?

2022-04-03 20:06 UTC, lgfa29 commented on README.md
> +| [aws_ecs_task_definition](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_task_definition) | resource | É um arquivo de texto `em formato JSON` que descreve um ou ma
```suggestion
| [aws_ecs_task_definition](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_task_definition) | resource | É um arquivo de texto em formato JSON que descreve uma ou mais características dos contêineres. |
```

2022-04-03 20:06 UTC, lgfa29 commented on README.md
> +| [aws_appautoscaling_policy](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appautoscaling_policy) | resource | O Auto Scaling é um serviço que permite aumentar ou dimin
```suggestion
| [aws_appautoscaling_policy](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appautoscaling_policy) | resource | O Auto Scaling policy define as regras de escala de um serviço Auto Scaling . |
```

2022-04-03 20:06 UTC, lgfa29 commented on README.md
> +| [aws_lb_target_group](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lbhttps://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_target_group) | re
```suggestion
| [aws_lb_target_group](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_target_group) | resource | Fornece um grupo de destino que onde o load balance consiga encaminhar requisições. |
```

2022-04-03 20:06 UTC, lgfa29 commented on README.md
> +| [variables](https://www.terraform.io/language/values/variables) | input | Serve como parâmetros para que um usuário possam personalizar o comportamento sem editar o código fonte. |
```suggestion
```

Acho que esses aqui não precisam porque são comuns a todos os módulos.

2022-04-03 20:06 UTC, lgfa29 commented on README.md
> +| fargate\_cpu | Número de CPUs usados na taskde finition | `number` | n/a | yes |
```suggestion
| fargate\_cpu | Número de CPUs usados na task definition | `number` | n/a | yes |
```

2022-04-03 20:06 UTC, lgfa29 commented on README.md
> +| template\_container | Um arquivo json que contém as definições do container | `list(object` | n/a | no |
```suggestion
| template\_container | Objetos que contém as definições dos containers | `list(object)` | n/a | yes |
```

Isso é uma lista de objects né?

2022-04-03 20:06 UTC, lgfa29 commented on autoscaling.tf
> +  depends_on         = [aws_ecs_service.service_cluster]
Essa dependência é necessária? Eu acho que o Terraform deveria pegar a dependência automaticamente já que é referenciado no `resource_id`.

2022-04-03 20:06 UTC, lgfa29 commented on autoscaling.tf
> +  min_capacity       = 1
Talvez no futuro seria lega ter esse valores como variáveis 🙂

2022-04-03 20:06 UTC, lgfa29 commented on autoscaling.tf
> +  depends_on = [aws_appautoscaling_target.ecs_target]
Essa dependência eu acho que não precisa também.

2022-04-03 20:06 UTC, lgfa29 commented on autoscaling.tf
> +    }
Eu não entendo muito desse resource, mas parece que a regra está igual ao `aws_appautoscaling_policy.up`? Isso daria algum conflito?

2022-04-03 20:06 UTC, lgfa29 commented on autoscaling.tf
> +  depends_on = [aws_appautoscaling_target.ecs_target]
Mais um `depends_on` que eu acho que não precisa.

2022-04-03 20:06 UTC, lgfa29 commented on autoscaling.tf
> +
```suggestion
```

2022-04-03 20:06 UTC, lgfa29 commented on autoscaling.tf
> +  name               = "dev-to-cpu"
```suggestion
  name               = "cpu"
```

Não sei se fui eu que não entendi o nome 😅

2022-04-03 20:06 UTC, lgfa29 commented on cloudwatch.tf
> +  name              = element(var.template_container.*.logConfiguration.options.awslogs-group, 0)
```suggestion
  name              = var.template_container[0].logConfiguration.options.awslogs-group
```

Se for sempre zero pode acessar direto. Mas também, se for sempre zero, precisa definir a variável como uma lista?

2022-04-03 20:06 UTC, lgfa29 commented on iamrole.tf
> +
```suggestion
```

2022-04-03 20:06 UTC, lgfa29 commented on outputs.tf
> -}
Acho que seria bom manter o arquivo como `outputs.tf` para deixar padronizado.

2022-04-03 20:06 UTC, lgfa29 commented on service.tf
> +
```suggestion
```

2022-04-03 20:06 UTC, lgfa29 commented on service.tf
> +    container_name   = element(var.template_container.*.name, 0)
```suggestion
    container_name   = var.template_container[0].name
```

2022-04-03 20:06 UTC, lgfa29 commented on sg.tf
> +resource "aws_security_group" "allow_acesso" {
```suggestion
resource "aws_security_group" "allow_access" {
```

Mais uma padronização.

2022-04-03 20:06 UTC, lgfa29 commented on sg.tf
> +  name        = element(var.template_container.*.name, 0)
```suggestion
  name        = var.template_container[0].name
```

2022-04-03 20:06 UTC, lgfa29 commented on versions.tf
> +}
Em geral é bom deixar que o módulo [herde](https://www.terraform.io/language/modules/develop/providers) o `provider` da configuração principal, então não precisa definir aqui. E aí a variável de `region` acho que nem precisa existir porque só é usada aqui?

2022-04-03 20:06 UTC, lgfa29 commented on local.tf
> +    System       = "api-tika"
Acho que esse valor seria melhor em uma variável.

2022-04-09 17:08 UTC, EzzioWMoreira commented on service.tf
> +    container_name   = element(var.template_container.*.name, 0)
@lgfa29 eu já tinha tentado utilizar o index [0] mas estoura o erro:
```shell
│ Error: Error in function call
│ 
│   on ../service.tf line 18, in resource "aws_ecs_service" "service_cluster":
│   18:     container_name   = element(var.template_container[0].name, 0)
│     ├────────────────
│     │ var.template_container[0].name is a string, known only after apply
│ 
│ Call to function "element" failed: cannot read elements from string.
```

2022-04-09 17:10 UTC, EzzioWMoreira commented on sg.tf
> +  name        = element(var.template_container.*.name, 0)
@lgfa29 eu já tinha tentado utilizar o index [0] mas estoura o erro:
```shell
│ Error: Error in function call
│ 
│   on ../service.tf line 18, in resource "aws_ecs_service" "service_cluster":
│   18:     container_name   = element(var.template_container[0].name, 0)
│     ├────────────────
│     │ var.template_container[0].name is a string, known only after apply
│ 
│ Call to function "element" failed: cannot read elements from string.
```

2022-04-24 16:16 UTC, lgfa29 commented on how-to-use-this-module/terrafile.tf
> +  cluster_name    = "mentoria"
Eu não sei se o linter pega esse arquivo, mas precisa dar um `terraform fmt` nesse bloco.

2022-04-30 17:04 UTC, chnacib commented
Refatorado para ter um Produto Viável Mínimo de acordo com a [demanda original](https://github.com/DadosAbertosDeFeira/maria-quiteria/issues/480).

### Alterações:
-  [x] Load Balancer apenas na API 
-  [x] Variável para template de cada container(imagem,nome)
-  [x] Variável para portas de cada container
-  [x] 1 Task-definition apenas para 3 containers rodando pois precisam se conectar entre si internamente (segundo o Gomex, o tika ainda não haverá autenticação)

2022-05-01 14:05 UTC, EzzioMoreira commented on autoscaling.tf
> +  min_capacity       = 1
Boa.

2022-05-01 14:12 UTC, EzzioMoreira commented on autoscaling.tf
> +  min_capacity       = 1
@lgfa29 Nós temos uma issue aberta para refactor do código. Vamos incluir sua sugestão.

2022-05-01 14:45 UTC, EzzioMoreira commented on autoscaling.tf
> +  depends_on         = [aws_ecs_service.service_cluster]
```suggestion
```

2022-05-01 14:50 UTC, EzzioMoreira commented on autoscaling.tf
> +  depends_on = [aws_appautoscaling_target.ecs_target]
```suggestion
```

2022-05-01 14:51 UTC, EzzioMoreira commented on autoscaling.tf
> +  depends_on = [aws_appautoscaling_target.ecs_target]
```suggestion
```

2022-05-01 15:04 UTC, EzzioMoreira commented on README.md
> +| template\_container | Um arquivo json que contém as definições do container | `list(object` | n/a | no |
Sim.

2022-05-01 15:44 UTC, EzzioMoreira commented
@chnacib Faz um fork do projeto da mentoria e cria uma nova brach para refatoração. :metal: 
https://github.com/mentoriaiac/iac-modulo-aws-ecs/pull/2#issuecomment-1114020521

2022-05-02 22:11 UTC, chnacib commented on README.md
> +| [variables](https://www.terraform.io/language/values/variables) | input | Serve como parâmetros para que um usuário possam personalizar o comportamento sem editar o código fonte. |
Decidimos que deixaremos essa parte para facilitar o entendimento de quem está começando com Terraform

2022-05-02 23:13 UTC, chnacib commented on autoscaling.tf
> +    }
É verdade, a condition estava igual mas com efeitos diferentes. Removido, e decidimos manter a policy de TargetTracking de cpu/memoria

2022-05-02 23:28 UTC, chnacib commented
MVP finalizado. Aguardando Review

2022-07-22 04:55 UTC, gomex requested changes
O PR está muito bom, mas esses secrets precisam necessariamente serem removidos do módulo de ECS. Essa lista precisa ser informada no lugar onde chama o módulo, que no caso atual será o repositório mariaquiteria.

2022-07-22 04:55 UTC, gomex commented on task-definition.tf
> +      secrets = [{
Esses secrets devem ser apresentados pelo uso do módulo. Essas variáveis não podem ser hardcoded dentro do módulo.

2022-07-22 04:55 UTC, gomex commented on task-definition.tf
> +      secrets = [{
Vc pode pegar uma variável que tem todas as informações que precisam ser passadas pelo usuário.

Eu não tentei ainda, mas algo mais ou menos assim:

```
secrets = var.secrets
```

E no input do secrets no modulo root (O que chama esse módulo) seria algo mais ou menos assim:

```
[     
        {
        "name" : "DJANGO_SECRET_KEY",
        "valueFrom" : data.aws_ssm_parameter.main["django_secret_key"].arn
        },
        {
        "name" : "DJANGO_SETTINGS_MODULE",
        "valueFrom" : data.aws_ssm_parameter.main["django_settings_module"].arn
        },
...
]   
```

2022-08-10 23:37 UTC, merged